create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(), file_name text not null, import_type text not null check (import_type in ('usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event')),
  import_mode text not null check (import_mode in ('append','upsert','replace')), total_rows integer not null default 0, success_rows integer not null default 0, warning_rows integer not null default 0, error_rows integer not null default 0,
  status text not null default 'PARSED' check (status in ('PARSED','VALIDATING','VALIDATED','IMPORTED','FAILED','ROLLED_BACK')), uploaded_by uuid references auth.users(id), uploaded_at timestamptz not null default now(), imported_at timestamptz, rolled_back_at timestamptz, forecast_stale_marked boolean not null default false
);
create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key, batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, row_number integer not null, original_data jsonb not null, mapped_data jsonb, validation_status text not null default 'PENDING' check (validation_status in ('PENDING','SUCCESS','WARNING','ERROR')), unique(batch_id,row_number)
);
create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key, batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, row_number integer not null, field_name text not null, error_code text not null, error_message text not null, severity text not null check (severity in ('WARNING','ERROR')), original_value text, created_at timestamptz not null default now()
);
create table if not exists core.column_mapping (
  mapping_id uuid primary key default gen_random_uuid(), import_type text not null, source_column text not null, target_column text not null, active boolean not null default true, created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(import_type,source_column,target_column)
);
create table if not exists core.import_row_backup (
  backup_id bigint generated by default as identity primary key, batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, target_table text not null, row_data jsonb not null, backup_reason text not null check (backup_reason in ('UPSERT','REPLACE'))
);
create index if not exists import_staging_batch_idx on core.import_staging(batch_id,row_number);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id,row_number);

create or replace function core.import_target_table(p_type text) returns text language sql immutable as $$
  select case p_type when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master' when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' when 'sales_order' then 'sales_order' when 'business_event' then 'business_event' end;
$$;
create or replace view core.v_import_supplier_reference as select distinct "공급업체코드" as supplier_id from raw.supplier_master where "공급업체코드" is not null;

create or replace function core.commit_import_batch(p_batch_id uuid)
returns void language plpgsql security definer set search_path = core, raw, pg_temp as $$
declare b core.upload_batch%rowtype; table_name text; r record; payload jsonb;
begin
  if not core.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  select * into b from core.upload_batch where batch_id=p_batch_id for update;
  if not found or b.status <> 'VALIDATED' or b.error_rows > 0 then raise exception '검증 완료 및 오류 0건인 batch만 적재할 수 있습니다.' using errcode='22023'; end if;
  table_name := core.import_target_table(b.import_type); if table_name is null then raise exception '지원하지 않는 Import Type입니다.'; end if;
  if b.import_mode='replace' then execute format('insert into core.import_row_backup(batch_id,target_table,row_data,backup_reason) select $1,$2,to_jsonb(t),''REPLACE'' from raw.%I t',table_name) using p_batch_id,table_name; execute format('delete from raw.%I',table_name); end if;
  for r in select row_number,mapped_data from core.import_staging where batch_id=p_batch_id and validation_status in ('SUCCESS','WARNING') order by row_number loop
    payload := r.mapped_data || jsonb_build_object('batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',coalesce(r.mapped_data->>'source_record_id',r.row_number::text));
    if b.import_type='inventory' then payload := jsonb_build_object('품목코드',payload->>'item_id','창고',payload->>'warehouse','현재고',payload->>'current_stock','기준일자',payload->>'reference_date','안전재고',payload->>'safety_stock','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='item_master' then payload := jsonb_build_object('품목코드',payload->>'item_id','품목명',payload->>'item_name','품목구분',payload->>'item_type','단위',payload->>'unit','supplier_id',payload->>'supplier_id','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='supplier_master' then payload := jsonb_build_object('공급업체코드',payload->>'supplier_id','공급업체명',payload->>'supplier_name','국가',payload->>'country','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='purchase_order' then payload := jsonb_build_object('발주번호',payload->>'source_record_id','발주일',payload->>'order_date','공급업체',payload->>'supplier_id','품목코드',payload->>'item_id','발주수량',payload->>'qty','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='goods_receipt' then payload := jsonb_build_object('입고번호',payload->>'source_record_id','품목코드',payload->>'item_id','입고수량',payload->>'qty','입고일',payload->>'receipt_date','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id'); end if;
    if b.import_mode='upsert' then execute format('insert into core.import_row_backup(batch_id,target_table,row_data,backup_reason) select $1,$2,to_jsonb(t),''UPSERT'' from raw.%I t where t.source_type=''FILE_UPLOAD'' and t.source_record_id=$3',table_name) using p_batch_id,table_name,payload->>'source_record_id'; execute format('delete from raw.%I where source_type=''FILE_UPLOAD'' and source_record_id=$1',table_name) using payload->>'source_record_id'; end if;
    execute format('insert into raw.%I select * from jsonb_populate_record(null::raw.%I,$1)',table_name,table_name) using payload;
  end loop;
  update core.upload_batch set status='IMPORTED', imported_at=now(), forecast_stale_marked=b.import_type in ('usage_history','sales_order','business_event') where batch_id=p_batch_id;
  if b.import_type in ('usage_history','sales_order','business_event') and to_regclass('core.forecast_run') is not null then execute 'update core.forecast_run set stale_at=now() where data_snapshot_at < now() and stale_at is null'; end if;
end; $$;

create or replace function core.rollback_import_batch(p_batch_id uuid)
returns void language plpgsql security definer set search_path = core, raw, pg_temp as $$
declare b core.upload_batch%rowtype; table_name text; r record;
begin
  if not core.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  select * into b from core.upload_batch where batch_id=p_batch_id for update; if not found or b.status <> 'IMPORTED' then raise exception '적재 완료 batch만 rollback할 수 있습니다.'; end if;
  table_name:=core.import_target_table(b.import_type); execute format('delete from raw.%I where batch_id=$1',table_name) using p_batch_id;
  for r in select row_data from core.import_row_backup where batch_id=p_batch_id order by backup_id loop execute format('insert into raw.%I select * from jsonb_populate_record(null::raw.%I,$1)',table_name,table_name) using r.row_data; end loop;
  update core.upload_batch set status='ROLLED_BACK',rolled_back_at=now() where batch_id=p_batch_id;
end; $$;

do $rls$ declare t text; begin foreach t in array array['upload_batch','import_staging','validation_error','column_mapping','import_row_backup'] loop execute format('alter table core.%I enable row level security',t); execute format('create policy %I on core.%I for select to authenticated using (core.is_active_user())',t||'_active_select',t); execute format('create policy %I on core.%I for all to authenticated using (core.is_admin()) with check (core.is_admin())',t||'_admin_mutation',t); end loop; end $rls$;
grant select,insert,update,delete on core.upload_batch,core.import_staging,core.validation_error,core.column_mapping,core.import_row_backup to authenticated;
grant select on core.v_import_supplier_reference to authenticated;
grant usage,select on all sequences in schema core to authenticated;
grant execute on function core.commit_import_batch(uuid),core.rollback_import_batch(uuid) to authenticated;
revoke execute on function core.commit_import_batch(uuid),core.rollback_import_batch(uuid) from anon;


